/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DaoOzliaMae.DaoEmpleado;
import DaoOzliaMae.DaoHerramienta;
import DaoOzliaMae.DaoMantenimiento;
import static DaoOzliaMae.DaoMantenimiento.listaMantenimientos;
import DaoOzliaMae.DaoRefaccion;
import Empleado.Empleado;
import Herramienta.Herramienta;
import Mantenimiento.Mantenimiento;
import Refaccion.Refaccion;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author celes
 */
public class RefaVer extends javax.swing.JFrame {

    /**
     * Creates new form EmpVer
     */
    public RefaVer() {
        initComponents();
        verTabla();
    }

    void verTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID refacción");
        modelo.addColumn("Descripción");
        modelo.addColumn("Marca");
        modelo.addColumn("Costo");
        modelo.addColumn("Centro Costos");
        modelo.addColumn("ID matto.");
        modelo.addColumn("ID herramienta");
        modelo.addColumn("Ubicación");
        modelo.addColumn("Marca Herramienta");
        modelo.addColumn("Realizo");
        
        TablaDatos.setModel(modelo);
        String datos[] = new String[10];
        
        List<Refaccion> listaRefacciones = new ArrayList<>();
        try {
            listaRefacciones = DaoRefaccion.listaRefacciones();
            for(Refaccion refaccion:listaRefacciones){
                Mantenimiento mantenimiento = DaoMantenimiento.buscar(refaccion.getMattoID());
                Empleado empleado = DaoEmpleado.nombre(mantenimiento.getEmpID());
                Herramienta herramienta = DaoHerramienta.ubicacion(mantenimiento.getHerrID());
                datos[0] = String.valueOf(refaccion.getRefaID());
                datos[1] = refaccion.getDescripcion();
                datos[2] = refaccion.getMarca();
                datos[3] = String.valueOf(refaccion.getCosto());
                datos[4] = String.valueOf(refaccion.getCc());
                datos[5] = String.valueOf(refaccion.getMattoID());
                datos[6] = String.valueOf(mantenimiento.getHerrID());
                datos[7] = herramienta.getUbicacion();
                datos[8] = herramienta.getMarca();
                datos[9] = empleado.getNombre();
                modelo.addRow(datos);
            }
            TablaDatos.setModel(modelo);  
        } catch (SQLException ex) {
            Logger.getLogger(RefaVer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
              
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TextHerrID = new javax.swing.JFormattedTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Tabla refacciones");

        TablaDatos.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaDatos);

        jButton2.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jButton3.setText("Restablecer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TextHerrID.setForeground(new java.awt.Color(51, 51, 51));
        TextHerrID.setText("ID de herramienta");
        TextHerrID.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N

        jButton5.setFont(new java.awt.Font("Candara Light", 1, 24)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextHerrID, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextHerrID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuOzLia ozLia = new MenuOzLia();
        ozLia.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        verTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int herrID = Integer.valueOf(TextHerrID.getText());

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID refacción");
        modelo.addColumn("Descripción");
        modelo.addColumn("Marca");
        modelo.addColumn("Costo");
        modelo.addColumn("Centro Costos");
        modelo.addColumn("ID matto.");
        modelo.addColumn("ID herramienta");
        modelo.addColumn("Ubicación");
        modelo.addColumn("Marca Herramienta");
        modelo.addColumn("Realizo");
        
        TablaDatos.setModel(modelo);
        String datos[] = new String[10];
        
        List<Mantenimiento> listaMantenimientos = new ArrayList<>();
        try {
            listaMantenimientos = DaoMantenimiento.buscarHerr(herrID);
            for(Mantenimiento mantenimiento:listaMantenimientos){
                List<Refaccion> listaRefacciones = new ArrayList<>();
                listaRefacciones = DaoRefaccion.buscar(mantenimiento.getMattoID());
                for(Refaccion refaccion:listaRefacciones){
                    Empleado empleado = DaoEmpleado.nombre(mantenimiento.getEmpID());
                    Herramienta herramienta = DaoHerramienta.ubicacion(mantenimiento.getHerrID());
                    datos[0] = String.valueOf(refaccion.getRefaID());
                    datos[1] = refaccion.getDescripcion();
                    datos[2] = refaccion.getMarca();
                    datos[3] = String.valueOf(refaccion.getCosto());
                    datos[4] = String.valueOf(refaccion.getCc());
                    datos[5] = String.valueOf(refaccion.getMattoID());
                    datos[6] = String.valueOf(mantenimiento.getHerrID());
                    datos[7] = herramienta.getUbicacion();
                    datos[8] = herramienta.getMarca();
                    datos[9] = empleado.getNombre();
                    modelo.addRow(datos);
                }
            }
            TablaDatos.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(HerrVer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RefaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RefaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RefaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RefaVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RefaVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JFormattedTextField TextHerrID;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
